networks:
  laravel:

services:
  #Vue
  nginx:
    image: nginx
    volumes:
      - "./vue-Frontend/dist:/usr/share/nginx/html"
      - "./docker/conf.d:/etc/nginx/conf.d"
    ports:
      - ${VITE_PORT}:80
  #Laravel
  web:
    image: nginx:1.23-alpine
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./laravel-Backend/:/www:rw
      - ./laravel-Backend/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./laravel-Backend/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel-Backend/docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - app
    networks:
      - laravel

  app:
    image: rcsnjszg/laravelapp:0.0.1-alpine
    build:
      context: ./laravel-Backend/docker/php
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - "./laravel-Backend:/www:rw"
      - "./laravel-Backend/docker/php/config/php.ini-production:${PHP_INI_DIR}/php.ini:ro"
    networks:
      - laravel

  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password --sql-mode="ANSI_QUOTES"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ="${TZ}"
    ports:
      - "${DB_PUBLIC_PORT}:3306"
    volumes:
      - "./laravel-Backend/docker/mysql/var/lib/mysql:/var/lib/mysql:rw"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:5.1-apache
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${DB_HOST}
    ports:
      - "${PMA_PORT}:80"
    volumes:
      - ./laravel-Backend/docker/phpmyadmin/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - laravel